export const SHIPPING_DISCLAIMER =
  'WE CANNOT SHIP TO THE FOLLOWING STATES DUE TO SHIPPING RESTRICTIONS: CALIFORNIA, OREGON, WASHINGTON, ARIZONA, ALASKA, HAWAII, IDAHO, PUERTO RICO, NEVADA, MONTANA, UTAH AND NEW MEXICO'
